# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diseño.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 710)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_Superior = QtWidgets.QFrame(self.frame)
        self.frame_Superior.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_Superior.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_Superior.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(53, 53, 79);\n"
"border-radius:20px;\n"
"}")
        self.frame_Superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Superior.setObjectName("frame_Superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_Superior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_Superior)
        self.label.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(567, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.minimizar = QtWidgets.QPushButton(self.frame_Superior)
        self.minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.minimizar.setStyleSheet("")
        self.minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image (3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizar.setIcon(icon)
        self.minimizar.setIconSize(QtCore.QSize(25, 25))
        self.minimizar.setObjectName("minimizar")
        self.horizontalLayout.addWidget(self.minimizar)
        self.restaurar = QtWidgets.QPushButton(self.frame_Superior)
        self.restaurar.setMinimumSize(QtCore.QSize(40, 40))
        self.restaurar.setStyleSheet("")
        self.restaurar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restaurar.setIcon(icon1)
        self.restaurar.setIconSize(QtCore.QSize(25, 25))
        self.restaurar.setObjectName("restaurar")
        self.horizontalLayout.addWidget(self.restaurar)
        self.maximizar = QtWidgets.QPushButton(self.frame_Superior)
        self.maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.maximizar.setStyleSheet("")
        self.maximizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizar.setIcon(icon2)
        self.maximizar.setIconSize(QtCore.QSize(25, 25))
        self.maximizar.setObjectName("maximizar")
        self.horizontalLayout.addWidget(self.maximizar)
        self.cerrar = QtWidgets.QPushButton(self.frame_Superior)
        self.cerrar.setMinimumSize(QtCore.QSize(40, 40))
        self.cerrar.setStyleSheet("")
        self.cerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cerrar.setIcon(icon3)
        self.cerrar.setIconSize(QtCore.QSize(25, 25))
        self.cerrar.setObjectName("cerrar")
        self.horizontalLayout.addWidget(self.cerrar)
        self.verticalLayout_2.addWidget(self.frame_Superior)
        self.frame_Inferior = QtWidgets.QFrame(self.frame)
        self.frame_Inferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Inferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Inferior.setObjectName("frame_Inferior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_Inferior)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_lateral = QtWidgets.QFrame(self.frame_Inferior)
        self.frame_lateral.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_lateral.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_lateral.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(76, 76, 76);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"}")
        self.frame_lateral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lateral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lateral.setObjectName("frame_lateral")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_lateral)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lateralAgregarCliente = QtWidgets.QPushButton(self.frame_lateral)
        self.lateralAgregarCliente.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lateralAgregarCliente.setObjectName("lateralAgregarCliente")
        self.verticalLayout_4.addWidget(self.lateralAgregarCliente)
        self.lateralMostrarCliente = QtWidgets.QPushButton(self.frame_lateral)
        self.lateralMostrarCliente.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lateralMostrarCliente.setObjectName("lateralMostrarCliente")
        self.verticalLayout_4.addWidget(self.lateralMostrarCliente)
        self.lateralAgregarProducto = QtWidgets.QPushButton(self.frame_lateral)
        self.lateralAgregarProducto.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lateralAgregarProducto.setObjectName("lateralAgregarProducto")
        self.verticalLayout_4.addWidget(self.lateralAgregarProducto)
        self.lateralMostrarProducto = QtWidgets.QPushButton(self.frame_lateral)
        self.lateralMostrarProducto.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lateralMostrarProducto.setObjectName("lateralMostrarProducto")
        self.verticalLayout_4.addWidget(self.lateralMostrarProducto)
        self.lateralFacturas = QtWidgets.QPushButton(self.frame_lateral)
        self.lateralFacturas.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lateralFacturas.setObjectName("lateralFacturas")
        self.verticalLayout_4.addWidget(self.lateralFacturas)
        self.horizontalLayout_2.addWidget(self.frame_lateral)
        self.frame_contenedor = QtWidgets.QFrame(self.frame_Inferior)
        self.frame_contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contenedor.setObjectName("frame_contenedor")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_contenedor)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_contenedor)
        self.stackedWidget.setStyleSheet("background-color: rgb(126, 126, 126);\n"
"\n"
"QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.cliente = QtWidgets.QWidget()
        self.cliente.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}")
        self.cliente.setObjectName("cliente")
        self.groupBoxAgregarC = QtWidgets.QGroupBox(self.cliente)
        self.groupBoxAgregarC.setGeometry(QtCore.QRect(40, 30, 711, 231))
        self.groupBoxAgregarC.setStyleSheet("QGroupBox{\n"
"font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(7, 7, 7);\n"
"border-radius: 5;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(53, 53, 79);\n"
"border-radius:20px;\n"
"}")
        self.groupBoxAgregarC.setObjectName("groupBoxAgregarC")
        self.cedula = QtWidgets.QLineEdit(self.groupBoxAgregarC)
        self.cedula.setGeometry(QtCore.QRect(150, 100, 151, 21))
        self.cedula.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.cedula.setText("")
        self.cedula.setObjectName("cedula")
        self.nombre = QtWidgets.QLineEdit(self.groupBoxAgregarC)
        self.nombre.setGeometry(QtCore.QRect(150, 170, 221, 21))
        self.nombre.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.nombre.setText("")
        self.nombre.setObjectName("nombre")
        self.label_2 = QtWidgets.QLabel(self.groupBoxAgregarC)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 81, 21))
        self.label_2.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBoxAgregarC)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 101, 21))
        self.label_3.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_3.setObjectName("label_3")
        self.btAgregarCliente = QtWidgets.QPushButton(self.groupBoxAgregarC)
        self.btAgregarCliente.setGeometry(QtCore.QRect(500, 100, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.btAgregarCliente.setFont(font)
        self.btAgregarCliente.setStyleSheet("font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"\n"
"")
        self.btAgregarCliente.setObjectName("btAgregarCliente")
        self.groupBox_EliminarC = QtWidgets.QGroupBox(self.cliente)
        self.groupBox_EliminarC.setGeometry(QtCore.QRect(40, 350, 711, 201))
        self.groupBox_EliminarC.setStyleSheet("QGroupBox{\n"
"font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(7, 7, 7);\n"
"border-radius: 5;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(53, 53, 79);\n"
"border-radius:20px;\n"
"}\n"
"")
        self.groupBox_EliminarC.setObjectName("groupBox_EliminarC")
        self.cedulaEli = QtWidgets.QLineEdit(self.groupBox_EliminarC)
        self.cedulaEli.setGeometry(QtCore.QRect(160, 100, 151, 21))
        self.cedulaEli.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"\n"
"font: 87 12pt \"Arial Black\";\n"
"")
        self.cedulaEli.setText("")
        self.cedulaEli.setObjectName("cedulaEli")
        self.label_6 = QtWidgets.QLabel(self.groupBox_EliminarC)
        self.label_6.setGeometry(QtCore.QRect(50, 100, 81, 21))
        self.label_6.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.btEliminar = QtWidgets.QPushButton(self.groupBox_EliminarC)
        self.btEliminar.setGeometry(QtCore.QRect(500, 60, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.btEliminar.setFont(font)
        self.btEliminar.setStyleSheet("font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.btEliminar.setObjectName("btEliminar")
        self.stackedWidget.addWidget(self.cliente)
        self.MostrarCli = QtWidgets.QWidget()
        self.MostrarCli.setObjectName("MostrarCli")
        self.tablaClientes = QtWidgets.QTableWidget(self.MostrarCli)
        self.tablaClientes.setGeometry(QtCore.QRect(40, 30, 731, 571))
        self.tablaClientes.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.tablaClientes.setShowGrid(True)
        self.tablaClientes.setObjectName("tablaClientes")
        self.tablaClientes.setColumnCount(2)
        self.tablaClientes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaClientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaClientes.setHorizontalHeaderItem(1, item)
        self.tablaClientes.horizontalHeader().setSortIndicatorShown(False)
        self.tablaClientes.horizontalHeader().setStretchLastSection(True)
        self.tablaClientes.verticalHeader().setVisible(False)
        self.stackedWidget.addWidget(self.MostrarCli)
        self.Producto = QtWidgets.QWidget()
        self.Producto.setObjectName("Producto")
        self.groupBox = QtWidgets.QGroupBox(self.Producto)
        self.groupBox.setGeometry(QtCore.QRect(50, 20, 701, 171))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(7, 7, 7);\n"
"border-radius: 5;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(53, 53, 79);\n"
"border-radius:20px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btAntibiotico = QtWidgets.QPushButton(self.groupBox)
        self.btAntibiotico.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.btAntibiotico.setObjectName("btAntibiotico")
        self.horizontalLayout_3.addWidget(self.btAntibiotico)
        self.btFertilizante = QtWidgets.QPushButton(self.groupBox)
        self.btFertilizante.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.btFertilizante.setObjectName("btFertilizante")
        self.horizontalLayout_3.addWidget(self.btFertilizante)
        self.btPlagas = QtWidgets.QPushButton(self.groupBox)
        self.btPlagas.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.btPlagas.setObjectName("btPlagas")
        self.horizontalLayout_3.addWidget(self.btPlagas)
        self.stackedWidgetPro = QtWidgets.QStackedWidget(self.Producto)
        self.stackedWidgetPro.setGeometry(QtCore.QRect(40, 220, 731, 411))
        self.stackedWidgetPro.setObjectName("stackedWidgetPro")
        self.pgAntibiotico = QtWidgets.QWidget()
        self.pgAntibiotico.setObjectName("pgAntibiotico")
        self.groupBox_2 = QtWidgets.QGroupBox(self.pgAntibiotico)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 701, 381))
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(7, 7, 7);\n"
"border-radius: 5;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(53, 53, 79);\n"
"border-radius:20px;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.labelanti = QtWidgets.QLabel(self.groupBox_2)
        self.labelanti.setGeometry(QtCore.QRect(30, 120, 101, 21))
        self.labelanti.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.labelanti.setObjectName("labelanti")
        self.nombreAntibiotico = QtWidgets.QLineEdit(self.groupBox_2)
        self.nombreAntibiotico.setGeometry(QtCore.QRect(140, 120, 221, 21))
        self.nombreAntibiotico.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.nombreAntibiotico.setText("")
        self.nombreAntibiotico.setObjectName("nombreAntibiotico")
        self.dosisAntibiotico = QtWidgets.QLineEdit(self.groupBox_2)
        self.dosisAntibiotico.setGeometry(QtCore.QRect(510, 120, 131, 21))
        self.dosisAntibiotico.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.dosisAntibiotico.setText("")
        self.dosisAntibiotico.setObjectName("dosisAntibiotico")
        self.labelanti_2 = QtWidgets.QLabel(self.groupBox_2)
        self.labelanti_2.setGeometry(QtCore.QRect(400, 120, 101, 21))
        self.labelanti_2.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.labelanti_2.setObjectName("labelanti_2")
        self.labelanti_3 = QtWidgets.QLabel(self.groupBox_2)
        self.labelanti_3.setGeometry(QtCore.QRect(400, 190, 101, 21))
        self.labelanti_3.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.labelanti_3.setObjectName("labelanti_3")
        self.precioAntibiotico = QtWidgets.QLineEdit(self.groupBox_2)
        self.precioAntibiotico.setGeometry(QtCore.QRect(510, 190, 131, 21))
        self.precioAntibiotico.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.precioAntibiotico.setText("")
        self.precioAntibiotico.setObjectName("precioAntibiotico")
        self.labelanti_4 = QtWidgets.QLabel(self.groupBox_2)
        self.labelanti_4.setGeometry(QtCore.QRect(30, 190, 171, 21))
        self.labelanti_4.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.labelanti_4.setObjectName("labelanti_4")
        self.tipoAnimal = QtWidgets.QComboBox(self.groupBox_2)
        self.tipoAnimal.setGeometry(QtCore.QRect(210, 190, 151, 22))
        self.tipoAnimal.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 10pt \"Arial Black\";\n"
"border-radius: 5;")
        self.tipoAnimal.setObjectName("tipoAnimal")
        self.tipoAnimal.addItem("")
        self.tipoAnimal.addItem("")
        self.tipoAnimal.addItem("")
        self.tipoAnimal.addItem("")
        self.btAgregarPro = QtWidgets.QPushButton(self.groupBox_2)
        self.btAgregarPro.setGeometry(QtCore.QRect(450, 260, 181, 61))
        self.btAgregarPro.setStyleSheet("font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.btAgregarPro.setObjectName("btAgregarPro")
        self.stackedWidgetPro.addWidget(self.pgAntibiotico)
        self.pgFertilizante = QtWidgets.QWidget()
        self.pgFertilizante.setObjectName("pgFertilizante")
        self.groupBox_3 = QtWidgets.QGroupBox(self.pgFertilizante)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 701, 381))
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(7, 7, 7);\n"
"border-radius: 5;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(53, 53, 79);\n"
"border-radius:20px;\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.labelanti_9 = QtWidgets.QLabel(self.groupBox_3)
        self.labelanti_9.setGeometry(QtCore.QRect(30, 100, 101, 21))
        self.labelanti_9.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.labelanti_9.setObjectName("labelanti_9")
        self.ICAFertilizante = QtWidgets.QLineEdit(self.groupBox_3)
        self.ICAFertilizante.setGeometry(QtCore.QRect(90, 100, 151, 21))
        self.ICAFertilizante.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.ICAFertilizante.setText("")
        self.ICAFertilizante.setObjectName("ICAFertilizante")
        self.nombreFertilizante = QtWidgets.QLineEdit(self.groupBox_3)
        self.nombreFertilizante.setGeometry(QtCore.QRect(400, 100, 201, 21))
        self.nombreFertilizante.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.nombreFertilizante.setText("")
        self.nombreFertilizante.setObjectName("nombreFertilizante")
        self.labelanti_10 = QtWidgets.QLabel(self.groupBox_3)
        self.labelanti_10.setGeometry(QtCore.QRect(290, 100, 101, 21))
        self.labelanti_10.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.labelanti_10.setObjectName("labelanti_10")
        self.labelanti_11 = QtWidgets.QLabel(self.groupBox_3)
        self.labelanti_11.setGeometry(QtCore.QRect(30, 180, 131, 21))
        self.labelanti_11.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.labelanti_11.setObjectName("labelanti_11")
        self.frecuenciaFertilizante = QtWidgets.QLineEdit(self.groupBox_3)
        self.frecuenciaFertilizante.setGeometry(QtCore.QRect(170, 180, 121, 21))
        self.frecuenciaFertilizante.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.frecuenciaFertilizante.setText("")
        self.frecuenciaFertilizante.setObjectName("frecuenciaFertilizante")
        self.labelanti_12 = QtWidgets.QLabel(self.groupBox_3)
        self.labelanti_12.setGeometry(QtCore.QRect(360, 180, 131, 21))
        self.labelanti_12.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.labelanti_12.setObjectName("labelanti_12")
        self.precioFertilizante = QtWidgets.QLineEdit(self.groupBox_3)
        self.precioFertilizante.setGeometry(QtCore.QRect(500, 180, 121, 21))
        self.precioFertilizante.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.precioFertilizante.setText("")
        self.precioFertilizante.setObjectName("precioFertilizante")
        self.labelanti_13 = QtWidgets.QLabel(self.groupBox_3)
        self.labelanti_13.setGeometry(QtCore.QRect(30, 260, 211, 21))
        self.labelanti_13.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.labelanti_13.setObjectName("labelanti_13")
        self.ultimaApliFertilizante = QtWidgets.QLineEdit(self.groupBox_3)
        self.ultimaApliFertilizante.setGeometry(QtCore.QRect(250, 260, 131, 21))
        self.ultimaApliFertilizante.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.ultimaApliFertilizante.setText("")
        self.ultimaApliFertilizante.setObjectName("ultimaApliFertilizante")
        self.btAgregarFer = QtWidgets.QPushButton(self.groupBox_3)
        self.btAgregarFer.setGeometry(QtCore.QRect(460, 280, 181, 61))
        self.btAgregarFer.setStyleSheet("font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.btAgregarFer.setObjectName("btAgregarFer")
        self.stackedWidgetPro.addWidget(self.pgFertilizante)
        self.pgPlagas = QtWidgets.QWidget()
        self.pgPlagas.setObjectName("pgPlagas")
        self.groupBox_4 = QtWidgets.QGroupBox(self.pgPlagas)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 20, 701, 371))
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(7, 7, 7);\n"
"border-radius: 5;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(53, 53, 79);\n"
"border-radius:20px;\n"
"}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.ICAPlagas = QtWidgets.QLineEdit(self.groupBox_4)
        self.ICAPlagas.setGeometry(QtCore.QRect(90, 120, 151, 21))
        self.ICAPlagas.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.ICAPlagas.setText("")
        self.ICAPlagas.setObjectName("ICAPlagas")
        self.labelanti_14 = QtWidgets.QLabel(self.groupBox_4)
        self.labelanti_14.setGeometry(QtCore.QRect(30, 120, 51, 21))
        self.labelanti_14.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.labelanti_14.setObjectName("labelanti_14")
        self.labelanti_17 = QtWidgets.QLabel(self.groupBox_4)
        self.labelanti_17.setGeometry(QtCore.QRect(40, 190, 131, 21))
        self.labelanti_17.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.labelanti_17.setObjectName("labelanti_17")
        self.labelanti_16 = QtWidgets.QLabel(self.groupBox_4)
        self.labelanti_16.setGeometry(QtCore.QRect(300, 130, 101, 21))
        self.labelanti_16.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.labelanti_16.setObjectName("labelanti_16")
        self.precioPlaga = QtWidgets.QLineEdit(self.groupBox_4)
        self.precioPlaga.setGeometry(QtCore.QRect(510, 190, 121, 21))
        self.precioPlaga.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.precioPlaga.setText("")
        self.precioPlaga.setObjectName("precioPlaga")
        self.nombrePlaga = QtWidgets.QLineEdit(self.groupBox_4)
        self.nombrePlaga.setGeometry(QtCore.QRect(410, 130, 201, 21))
        self.nombrePlaga.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.nombrePlaga.setText("")
        self.nombrePlaga.setObjectName("nombrePlaga")
        self.labelanti_15 = QtWidgets.QLabel(self.groupBox_4)
        self.labelanti_15.setGeometry(QtCore.QRect(370, 190, 131, 21))
        self.labelanti_15.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.labelanti_15.setObjectName("labelanti_15")
        self.frecuenciaPlaga = QtWidgets.QLineEdit(self.groupBox_4)
        self.frecuenciaPlaga.setGeometry(QtCore.QRect(180, 190, 121, 21))
        self.frecuenciaPlaga.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.frecuenciaPlaga.setText("")
        self.frecuenciaPlaga.setObjectName("frecuenciaPlaga")
        self.labelanti_18 = QtWidgets.QLabel(self.groupBox_4)
        self.labelanti_18.setGeometry(QtCore.QRect(40, 260, 111, 21))
        self.labelanti_18.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.labelanti_18.setObjectName("labelanti_18")
        self.carenciaPlaga = QtWidgets.QLineEdit(self.groupBox_4)
        self.carenciaPlaga.setGeometry(QtCore.QRect(170, 260, 201, 21))
        self.carenciaPlaga.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.carenciaPlaga.setText("")
        self.carenciaPlaga.setObjectName("carenciaPlaga")
        self.btAgregarPlaga = QtWidgets.QPushButton(self.groupBox_4)
        self.btAgregarPlaga.setGeometry(QtCore.QRect(460, 270, 181, 61))
        self.btAgregarPlaga.setStyleSheet("font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.btAgregarPlaga.setObjectName("btAgregarPlaga")
        self.stackedWidgetPro.addWidget(self.pgPlagas)
        self.stackedWidget.addWidget(self.Producto)
        self.MostrarPro = QtWidgets.QWidget()
        self.MostrarPro.setObjectName("MostrarPro")
        self.groupBox_5 = QtWidgets.QGroupBox(self.MostrarPro)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 0, 811, 651))
        self.groupBox_5.setStyleSheet("QGroupBox{\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(7, 7, 7);\n"
"border-radius: 5;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(53, 53, 79);\n"
"border-radius:20px;\n"
"}")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.tablaAntibioticos = QtWidgets.QTableWidget(self.groupBox_5)
        self.tablaAntibioticos.setGeometry(QtCore.QRect(50, 60, 711, 141))
        self.tablaAntibioticos.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.tablaAntibioticos.setObjectName("tablaAntibioticos")
        self.tablaAntibioticos.setColumnCount(4)
        self.tablaAntibioticos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaAntibioticos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaAntibioticos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaAntibioticos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaAntibioticos.setHorizontalHeaderItem(3, item)
        self.tablaAntibioticos.horizontalHeader().setVisible(False)
        self.tablaAntibioticos.horizontalHeader().setCascadingSectionResizes(False)
        self.tablaAntibioticos.horizontalHeader().setDefaultSectionSize(177)
        self.tablaAntibioticos.horizontalHeader().setHighlightSections(True)
        self.tablaAntibioticos.horizontalHeader().setSortIndicatorShown(False)
        self.tablaAntibioticos.horizontalHeader().setStretchLastSection(False)
        self.tablaPlagas = QtWidgets.QTableWidget(self.groupBox_5)
        self.tablaPlagas.setGeometry(QtCore.QRect(50, 460, 711, 151))
        self.tablaPlagas.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.tablaPlagas.setObjectName("tablaPlagas")
        self.tablaPlagas.setColumnCount(5)
        self.tablaPlagas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaPlagas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaPlagas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaPlagas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaPlagas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaPlagas.setHorizontalHeaderItem(4, item)
        self.tablaPlagas.horizontalHeader().setDefaultSectionSize(141)
        self.tablaFertilizante = QtWidgets.QTableWidget(self.groupBox_5)
        self.tablaFertilizante.setGeometry(QtCore.QRect(40, 260, 731, 141))
        self.tablaFertilizante.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.tablaFertilizante.setObjectName("tablaFertilizante")
        self.tablaFertilizante.setColumnCount(5)
        self.tablaFertilizante.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaFertilizante.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaFertilizante.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaFertilizante.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaFertilizante.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tablaFertilizante.setHorizontalHeaderItem(4, item)
        self.tablaFertilizante.horizontalHeader().setDefaultSectionSize(145)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(50, 20, 141, 31))
        self.label_4.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(60, 220, 151, 31))
        self.label_5.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(50, 430, 321, 31))
        self.label_7.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.MostrarPro)
        self.Facturas = QtWidgets.QWidget()
        self.Facturas.setObjectName("Facturas")
        self.groupBox_6 = QtWidgets.QGroupBox(self.Facturas)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 781, 191))
        self.groupBox_6.setStyleSheet("QGroupBox{\n"
"font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(7, 7, 7);\n"
"border-radius: 5;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(53, 53, 79);\n"
"border-radius:20px;\n"
"}")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 241, 31))
        self.label_8.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.nombreProComprar = QtWidgets.QLineEdit(self.groupBox_6)
        self.nombreProComprar.setGeometry(QtCore.QRect(250, 80, 171, 21))
        self.nombreProComprar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.nombreProComprar.setText("")
        self.nombreProComprar.setObjectName("nombreProComprar")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(440, 70, 81, 31))
        self.label_9.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.fechaFactura = QtWidgets.QLineEdit(self.groupBox_6)
        self.fechaFactura.setGeometry(QtCore.QRect(530, 80, 171, 21))
        self.fechaFactura.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.fechaFactura.setText("")
        self.fechaFactura.setObjectName("fechaFactura")
        self.facturaCliente = QtWidgets.QLineEdit(self.groupBox_6)
        self.facturaCliente.setGeometry(QtCore.QRect(250, 150, 171, 21))
        self.facturaCliente.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.facturaCliente.setText("")
        self.facturaCliente.setObjectName("facturaCliente")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(40, 140, 171, 31))
        self.label_10.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.btCrearFactura = QtWidgets.QPushButton(self.groupBox_6)
        self.btCrearFactura.setGeometry(QtCore.QRect(530, 120, 181, 61))
        self.btCrearFactura.setStyleSheet("font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.btCrearFactura.setObjectName("btCrearFactura")
        self.groupBox_7 = QtWidgets.QGroupBox(self.Facturas)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 220, 781, 411))
        self.groupBox_7.setStyleSheet("QGroupBox{\n"
"font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(7, 7, 7);\n"
"border-radius: 5;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(53, 53, 79);\n"
"border-radius:20px;\n"
"}")
        self.groupBox_7.setObjectName("groupBox_7")
        self.cedulaMostrarFacturas = QtWidgets.QLineEdit(self.groupBox_7)
        self.cedulaMostrarFacturas.setGeometry(QtCore.QRect(250, 70, 171, 21))
        self.cedulaMostrarFacturas.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 12pt \"Arial Black\";")
        self.cedulaMostrarFacturas.setText("")
        self.cedulaMostrarFacturas.setObjectName("cedulaMostrarFacturas")
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setGeometry(QtCore.QRect(40, 60, 171, 31))
        self.label_11.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_11.setObjectName("label_11")
        self.btMostraFactura = QtWidgets.QPushButton(self.groupBox_7)
        self.btMostraFactura.setGeometry(QtCore.QRect(540, 30, 181, 61))
        self.btMostraFactura.setStyleSheet("font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.btMostraFactura.setObjectName("btMostraFactura")
        self.tablaFacturas = QtWidgets.QTableWidget(self.groupBox_7)
        self.tablaFacturas.setGeometry(QtCore.QRect(40, 110, 691, 201))
        self.tablaFacturas.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.tablaFacturas.setShowGrid(True)
        self.tablaFacturas.setObjectName("tablaFacturas")
        self.tablaFacturas.setColumnCount(3)
        self.tablaFacturas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaFacturas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaFacturas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaFacturas.setHorizontalHeaderItem(2, item)
        self.tablaFacturas.horizontalHeader().setDefaultSectionSize(120)
        self.tablaFacturas.horizontalHeader().setStretchLastSection(True)
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setGeometry(QtCore.QRect(40, 340, 231, 31))
        self.label_12.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.precioTotal = QtWidgets.QLabel(self.groupBox_7)
        self.precioTotal.setGeometry(QtCore.QRect(290, 340, 231, 31))
        self.precioTotal.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.precioTotal.setText("")
        self.precioTotal.setObjectName("precioTotal")
        self.stackedWidget.addWidget(self.Facturas)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_contenedor)
        self.verticalLayout_2.addWidget(self.frame_Inferior)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        self.stackedWidgetPro.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Facturacion Tienda Agricola"))
        self.lateralAgregarCliente.setText(_translate("MainWindow", "Agregar Cliente"))
        self.lateralMostrarCliente.setText(_translate("MainWindow", "Mostrar Clientes"))
        self.lateralAgregarProducto.setText(_translate("MainWindow", "Agregar Producto"))
        self.lateralMostrarProducto.setText(_translate("MainWindow", "Mostrar Productos"))
        self.lateralFacturas.setText(_translate("MainWindow", "Facturas"))
        self.groupBoxAgregarC.setTitle(_translate("MainWindow", "Agregar Cliente"))
        self.label_2.setText(_translate("MainWindow", "Cedula:"))
        self.label_3.setText(_translate("MainWindow", "Nombre:"))
        self.btAgregarCliente.setText(_translate("MainWindow", "Agregar"))
        self.groupBox_EliminarC.setTitle(_translate("MainWindow", "Eliminar Cliente"))
        self.label_6.setText(_translate("MainWindow", "Cedula:"))
        self.btEliminar.setText(_translate("MainWindow", "Eliminar"))
        item = self.tablaClientes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cedula"))
        item = self.tablaClientes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        self.groupBox.setTitle(_translate("MainWindow", "Tipo de Producto"))
        self.btAntibiotico.setText(_translate("MainWindow", "Antibiotico"))
        self.btFertilizante.setText(_translate("MainWindow", "Fertilizante"))
        self.btPlagas.setText(_translate("MainWindow", "Control Plagas"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Agregar Antibiotico"))
        self.labelanti.setText(_translate("MainWindow", "Nombre:"))
        self.labelanti_2.setText(_translate("MainWindow", "Dosis:"))
        self.labelanti_3.setText(_translate("MainWindow", "Precio:"))
        self.labelanti_4.setText(_translate("MainWindow", "Tipo de animal:"))
        self.tipoAnimal.setItemText(0, _translate("MainWindow", "Seleccione..."))
        self.tipoAnimal.setItemText(1, _translate("MainWindow", "Bovinos"))
        self.tipoAnimal.setItemText(2, _translate("MainWindow", "Caprinos"))
        self.tipoAnimal.setItemText(3, _translate("MainWindow", "Porcinos"))
        self.btAgregarPro.setText(_translate("MainWindow", "Agregar"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Agregar Fertilizante"))
        self.labelanti_9.setText(_translate("MainWindow", "ICA:"))
        self.labelanti_10.setText(_translate("MainWindow", "Nombre:"))
        self.labelanti_11.setText(_translate("MainWindow", "Frecuencia: "))
        self.labelanti_12.setText(_translate("MainWindow", "Precio:"))
        self.labelanti_13.setText(_translate("MainWindow", "Ultima aplicacion:"))
        self.btAgregarFer.setText(_translate("MainWindow", "Agregar"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Agregar Control de Plagas"))
        self.labelanti_14.setText(_translate("MainWindow", "ICA:"))
        self.labelanti_17.setText(_translate("MainWindow", "Frecuencia: "))
        self.labelanti_16.setText(_translate("MainWindow", "Nombre:"))
        self.labelanti_15.setText(_translate("MainWindow", "Precio:"))
        self.labelanti_18.setText(_translate("MainWindow", "Carencia:"))
        self.btAgregarPlaga.setText(_translate("MainWindow", "Agregar"))
        item = self.tablaAntibioticos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tablaAntibioticos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Dosis"))
        item = self.tablaAntibioticos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tipo Animal"))
        item = self.tablaAntibioticos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Precio"))
        item = self.tablaPlagas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ICA"))
        item = self.tablaPlagas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tablaPlagas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Frecuencia"))
        item = self.tablaPlagas.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Carencia"))
        item = self.tablaPlagas.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Precio"))
        item = self.tablaFertilizante.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ICA"))
        item = self.tablaFertilizante.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tablaFertilizante.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Frecuencia"))
        item = self.tablaFertilizante.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "U.Aplicacion"))
        item = self.tablaFertilizante.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Precio"))
        self.label_4.setText(_translate("MainWindow", "Antibioticos:"))
        self.label_5.setText(_translate("MainWindow", "Fertilizantes:"))
        self.label_7.setText(_translate("MainWindow", "Producto control de Plagas:"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Facturacion/Comprar"))
        self.label_8.setText(_translate("MainWindow", "Nombre del producto"))
        self.label_9.setText(_translate("MainWindow", "Fecha:"))
        self.label_10.setText(_translate("MainWindow", "Cedula cliente:"))
        self.btCrearFactura.setText(_translate("MainWindow", "Crear"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Mostar Facturas Cliente"))
        self.label_11.setText(_translate("MainWindow", "Cedula cliente:"))
        self.btMostraFactura.setText(_translate("MainWindow", "Mostrar"))
        self.tablaFacturas.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.tablaFacturas.setSortingEnabled(False)
        item = self.tablaFacturas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Fecha"))
        item = self.tablaFacturas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Precio"))
        item = self.tablaFacturas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nombre del Producto"))
        self.label_12.setText(_translate("MainWindow", "Valor total facturas:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
