# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diseño.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 512)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_Superior = QtWidgets.QFrame(self.frame)
        self.frame_Superior.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_Superior.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_Superior.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(53, 53, 79);\n"
"border-radius:20px;\n"
"}")
        self.frame_Superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Superior.setObjectName("frame_Superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_Superior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_Superior)
        self.label.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(567, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.minimizar = QtWidgets.QPushButton(self.frame_Superior)
        self.minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.minimizar.setStyleSheet("")
        self.minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image (3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizar.setIcon(icon)
        self.minimizar.setIconSize(QtCore.QSize(25, 25))
        self.minimizar.setObjectName("minimizar")
        self.horizontalLayout.addWidget(self.minimizar)
        self.restaurar = QtWidgets.QPushButton(self.frame_Superior)
        self.restaurar.setMinimumSize(QtCore.QSize(40, 40))
        self.restaurar.setStyleSheet("")
        self.restaurar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restaurar.setIcon(icon1)
        self.restaurar.setIconSize(QtCore.QSize(25, 25))
        self.restaurar.setObjectName("restaurar")
        self.horizontalLayout.addWidget(self.restaurar)
        self.maximizar = QtWidgets.QPushButton(self.frame_Superior)
        self.maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.maximizar.setStyleSheet("")
        self.maximizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizar.setIcon(icon2)
        self.maximizar.setIconSize(QtCore.QSize(25, 25))
        self.maximizar.setObjectName("maximizar")
        self.horizontalLayout.addWidget(self.maximizar)
        self.cerrar = QtWidgets.QPushButton(self.frame_Superior)
        self.cerrar.setMinimumSize(QtCore.QSize(40, 40))
        self.cerrar.setStyleSheet("")
        self.cerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cerrar.setIcon(icon3)
        self.cerrar.setIconSize(QtCore.QSize(25, 25))
        self.cerrar.setObjectName("cerrar")
        self.horizontalLayout.addWidget(self.cerrar)
        self.verticalLayout_2.addWidget(self.frame_Superior)
        self.frame_Inferior = QtWidgets.QFrame(self.frame)
        self.frame_Inferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Inferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Inferior.setObjectName("frame_Inferior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_Inferior)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_lateral = QtWidgets.QFrame(self.frame_Inferior)
        self.frame_lateral.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_lateral.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_lateral.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(76, 76, 76);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"}")
        self.frame_lateral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lateral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lateral.setObjectName("frame_lateral")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_lateral)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lateralAgregarCliente = QtWidgets.QPushButton(self.frame_lateral)
        self.lateralAgregarCliente.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lateralAgregarCliente.setObjectName("lateralAgregarCliente")
        self.verticalLayout_4.addWidget(self.lateralAgregarCliente)
        self.lateralMostrarCliente = QtWidgets.QPushButton(self.frame_lateral)
        self.lateralMostrarCliente.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lateralMostrarCliente.setObjectName("lateralMostrarCliente")
        self.verticalLayout_4.addWidget(self.lateralMostrarCliente)
        self.lateralAgregarProducto = QtWidgets.QPushButton(self.frame_lateral)
        self.lateralAgregarProducto.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lateralAgregarProducto.setObjectName("lateralAgregarProducto")
        self.verticalLayout_4.addWidget(self.lateralAgregarProducto)
        self.lateralMostrarProducto = QtWidgets.QPushButton(self.frame_lateral)
        self.lateralMostrarProducto.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lateralMostrarProducto.setObjectName("lateralMostrarProducto")
        self.verticalLayout_4.addWidget(self.lateralMostrarProducto)
        self.lateralFacturas = QtWidgets.QPushButton(self.frame_lateral)
        self.lateralFacturas.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lateralFacturas.setObjectName("lateralFacturas")
        self.verticalLayout_4.addWidget(self.lateralFacturas)
        self.horizontalLayout_2.addWidget(self.frame_lateral)
        self.frame_contenedor = QtWidgets.QFrame(self.frame_Inferior)
        self.frame_contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contenedor.setObjectName("frame_contenedor")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_contenedor)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_contenedor)
        self.stackedWidget.setStyleSheet("background-color: rgb(126, 126, 126);\n"
"\n"
"QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.cliente = QtWidgets.QWidget()
        self.cliente.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}")
        self.cliente.setObjectName("cliente")
        self.groupBoxAgregarC = QtWidgets.QGroupBox(self.cliente)
        self.groupBoxAgregarC.setGeometry(QtCore.QRect(40, 10, 711, 181))
        self.groupBoxAgregarC.setStyleSheet("QGroupBox{\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(7, 7, 7);\n"
"border-radius: 5;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(53, 53, 79);\n"
"border-radius:20px;\n"
"}")
        self.groupBoxAgregarC.setObjectName("groupBoxAgregarC")
        self.cedula = QtWidgets.QLineEdit(self.groupBoxAgregarC)
        self.cedula.setGeometry(QtCore.QRect(150, 60, 151, 21))
        self.cedula.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cedula.setText("")
        self.cedula.setObjectName("cedula")
        self.nombre = QtWidgets.QLineEdit(self.groupBoxAgregarC)
        self.nombre.setGeometry(QtCore.QRect(150, 130, 221, 21))
        self.nombre.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.nombre.setText("")
        self.nombre.setObjectName("nombre")
        self.label_2 = QtWidgets.QLabel(self.groupBoxAgregarC)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 81, 21))
        self.label_2.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBoxAgregarC)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 101, 21))
        self.label_3.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_3.setObjectName("label_3")
        self.btAgregarCliente = QtWidgets.QPushButton(self.groupBoxAgregarC)
        self.btAgregarCliente.setGeometry(QtCore.QRect(500, 60, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.btAgregarCliente.setFont(font)
        self.btAgregarCliente.setStyleSheet("font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"\n"
"")
        self.btAgregarCliente.setObjectName("btAgregarCliente")
        self.groupBox_EliminarC = QtWidgets.QGroupBox(self.cliente)
        self.groupBox_EliminarC.setGeometry(QtCore.QRect(40, 230, 711, 181))
        self.groupBox_EliminarC.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius: 5\n"
"")
        self.groupBox_EliminarC.setObjectName("groupBox_EliminarC")
        self.cedulaEli = QtWidgets.QLineEdit(self.groupBox_EliminarC)
        self.cedulaEli.setGeometry(QtCore.QRect(160, 100, 151, 21))
        self.cedulaEli.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cedulaEli.setText("")
        self.cedulaEli.setObjectName("cedulaEli")
        self.label_6 = QtWidgets.QLabel(self.groupBox_EliminarC)
        self.label_6.setGeometry(QtCore.QRect(50, 100, 81, 21))
        self.label_6.setObjectName("label_6")
        self.btEliminar = QtWidgets.QPushButton(self.groupBox_EliminarC)
        self.btEliminar.setGeometry(QtCore.QRect(500, 60, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.btEliminar.setFont(font)
        self.btEliminar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 20pt \"Arial Black\";\n"
"border-radius:5px;\n"
"\n"
"")
        self.btEliminar.setObjectName("btEliminar")
        self.stackedWidget.addWidget(self.cliente)
        self.MostrarCli = QtWidgets.QWidget()
        self.MostrarCli.setObjectName("MostrarCli")
        self.tablaClientes = QtWidgets.QTableWidget(self.MostrarCli)
        self.tablaClientes.setGeometry(QtCore.QRect(70, 90, 631, 321))
        self.tablaClientes.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"")
        self.tablaClientes.setShowGrid(True)
        self.tablaClientes.setObjectName("tablaClientes")
        self.tablaClientes.setColumnCount(2)
        self.tablaClientes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaClientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaClientes.setHorizontalHeaderItem(1, item)
        self.tablaClientes.horizontalHeader().setSortIndicatorShown(False)
        self.tablaClientes.horizontalHeader().setStretchLastSection(True)
        self.tablaClientes.verticalHeader().setVisible(False)
        self.stackedWidget.addWidget(self.MostrarCli)
        self.Producto = QtWidgets.QWidget()
        self.Producto.setObjectName("Producto")
        self.stackedWidget.addWidget(self.Producto)
        self.MostrarPro = QtWidgets.QWidget()
        self.MostrarPro.setObjectName("MostrarPro")
        self.stackedWidget.addWidget(self.MostrarPro)
        self.Facturas = QtWidgets.QWidget()
        self.Facturas.setObjectName("Facturas")
        self.stackedWidget.addWidget(self.Facturas)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_contenedor)
        self.verticalLayout_2.addWidget(self.frame_Inferior)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Facturacion Tienda Agricola"))
        self.lateralAgregarCliente.setText(_translate("MainWindow", "Agregar Cliente"))
        self.lateralMostrarCliente.setText(_translate("MainWindow", "Mostrar Clientes"))
        self.lateralAgregarProducto.setText(_translate("MainWindow", "Agregar Producto"))
        self.lateralMostrarProducto.setText(_translate("MainWindow", "Mostrar Productos"))
        self.lateralFacturas.setText(_translate("MainWindow", "Facturas"))
        self.groupBoxAgregarC.setTitle(_translate("MainWindow", "Agregar Cliente"))
        self.label_2.setText(_translate("MainWindow", "Cedula:"))
        self.label_3.setText(_translate("MainWindow", "Nombre:"))
        self.btAgregarCliente.setText(_translate("MainWindow", "Agregar"))
        self.groupBox_EliminarC.setTitle(_translate("MainWindow", "Eliminar Cliente"))
        self.label_6.setText(_translate("MainWindow", "Cedula:"))
        self.btEliminar.setText(_translate("MainWindow", "Eliminar"))
        item = self.tablaClientes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cedula"))
        item = self.tablaClientes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
